FROM benediktkr/poetry:latest
MAINTAINER Benedikt Kristinsson <benedikt@lokun.is>


RUN mkdir /app
WORKDIR /app

#RUN apt-get update && apt-get install -y libczmq-dev libczmq

#RUN poetry config virtualenvs.create true

COPY poetry.lock pyproject.toml /app/
RUN poetry install --no-dev

ENTRYPOINT ["poetry"]
CMD ["build"]


# check this: https://jenkins.sudo.is/job/zflux/16/console
